### ISSUE TITLE
gulp default fails with Syntax Error: Unexpected token import in gulpfile.babel.js

### ISSUE THREAD

**Issue by satvidh** [paulsjv/leansheets#33]
Below is the full text of the error with node version 5.11.1. 

```
gulp default
[21:16:53] Requiring external module babel-register
/Users/satish.kumar/github/leansheets/gulpfile.babel.js:1
(function (exports, require, module, __filename, __dirname) { import gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/satish.kumar/github/leansheets/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/satish.kumar/github/leansheets/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)


```

**Comment by satvidh** [comment]
I will implement the steps on the following page to fix this issue.

https://babeljs.io/docs/plugins/preset-es2015/
